on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: dotnet build ./src/AutoFrontend.sln

      - name: Test
        run: dotnet test --no-build --no-restore ./src/AutoFrontend.sln

      - name: Format
        run: dotnet format --verify-no-changes --no-restore ./src/AutoFrontend.sln
