on:
  workflow_dispatch:
    inputs:
      version:
        description: "Nuget package version"
        required: true
        type: string
run-name: Release ${{ inputs.Version }}

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Pack
        run: dotnet pack -p:Version=${{ inputs.Version }} -o "./build" ./src/AutoFrontend.sln

      - name: Push to Nuget
        run: dotnet nuget push .\build\*.nupkg -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json
